# Generated by Django 5.0.2 on 2024-04-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="photo",
            field=models.ImageField(
                blank=True,
                default="default_profile_photo.jpg",
                null=True,
                upload_to="user_photos/",
            ),
        ),
    ]
